version: '3'
services:
  postgres:
    image: postgres:14.0
    container_name: push-ntf-postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 8081:80
  push-ntf-system:
    container_name: push-ntf-system
    hostname: push-ntf-system
    build: .
    restart: always
    ports:
      - "8080:8080"
